# Axolotl Guardian — asset build orchestrator.
#
#   blender --background --python blender/build.py -- [names...|all] [--preview] [--pack]
#
# GLBs land in $AXO_OUT/glb (default blender/out/glb); --pack embeds every GLB
# found there as base64 into js/assets-data.js so the game stays a zero-server,
# double-click-index.html build.

import base64
import importlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import lib            # noqa: E402
import characters     # noqa: E402
import props          # noqa: E402
for m in (lib, characters, props):
    importlib.reload(m)

ASSETS = {}
ASSETS.update(characters.ASSETS)
ASSETS.update(props.ASSETS)

OUT = os.environ.get('AXO_OUT', os.path.join(HERE, 'out'))
GLB_DIR = os.path.join(OUT, 'glb')
PREV_DIR = os.path.join(OUT, 'preview')


def pack():
    data = {}
    for f in sorted(os.listdir(GLB_DIR)):
        if f.endswith('.glb'):
            with open(os.path.join(GLB_DIR, f), 'rb') as fh:
                data[f[:-4]] = base64.b64encode(fh.read()).decode()
    lines = ['// GENERATED by blender/build.py — embedded GLB assets, do not edit.',
             'window.ASSET_DATA = {']
    for k, v in data.items():
        lines.append('  %s: %s,' % (json.dumps(k), json.dumps(v)))
    lines.append('};')
    path = os.path.normpath(os.path.join(HERE, '..', 'js', 'assets-data.js'))
    with open(path, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')
    total = sum(len(v) for v in data.values())
    print('PACKED %d assets -> %s (%d KB base64)' % (len(data), path, total // 1024))


def main():
    argv = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
    flags = {a for a in argv if a.startswith('--')}
    names = [a for a in argv if not a.startswith('--')]
    if not names or names == ['all']:
        names = list(ASSETS)
    unknown = [n for n in names if n not in ASSETS]
    if unknown:
        print('UNKNOWN ASSETS:', unknown)
        print('Available:', sorted(ASSETS))
        sys.exit(1)

    os.makedirs(GLB_DIR, exist_ok=True)
    os.makedirs(PREV_DIR, exist_ok=True)
    for n in names:
        lib.reset()
        spec = ASSETS[n]
        fn, opts = (spec if isinstance(spec, tuple) else (spec, {}))
        roots = fn()
        glb = lib.export_glb(os.path.join(GLB_DIR, n + '.glb'), roots)
        size = os.path.getsize(glb)
        print('BUILT %s (%d KB)' % (n, size // 1024))
        if '--preview' in flags:
            lib.preview(os.path.join(PREV_DIR, n + '.png'), roots, **opts)
            print('PREVIEW %s' % n)
    if '--pack' in flags:
        pack()


main()
